export default function Head() {
  return (
    <>
      <title>AirBnb</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      {/* TODO: */}
      <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    </>
  );
}
